/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/exercise/arm_curl copy 2.vue')['default']
    Arm_curl: typeof import('./src/components/exercise/arm_curl.vue')['default']
    copy: typeof import('./src/components/exercise/arm_curl copy.vue')['default']
    Exercise: typeof import('./src/components/exercise/exercise.vue')['default']
    Exercise_1: typeof import('./src/components/exercise/exercise_1.vue')['default']
    Exercise123: typeof import('./src/components/exercise/exercise123.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lunge: typeof import('./src/components/exercise/lunge.vue')['default']
    Main: typeof import('./src/components/main.vue')['default']
    Qr_code: typeof import('./src/components/qr_code.vue')['default']
    Shoulder_press: typeof import('./src/components/exercise/shoulder_press.vue')['default']
    Shoulderpress: typeof import('./src/components/shoulderpress.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
